site_name: Jim Burris Data Portfolio
site_url: https://jimburris.github.io/data-portfolio/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: material/database-eye
  # favicon: assets/favicon.ico


  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: deep orange



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg      
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
# Content Tabs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
# Admonitions (aka Callouts)
  - admonition
  - pymdownx.details


extra:
  social:
    - icon: simple/github
      # link: https://youtube.com/@james-willett
    # - icon: simple/youtube
    #   link: https://youtube.com/@james-willett
    # - icon: simple/linkedin
    #   link: https://linkedin.com/in/willettjames

copyright: Copyright &copy; 2025 Jim Burris